version: '3.8'

services:
  spring-boot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-api
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-30f9087-cristianbozomitu202-c787.f.aivencloud.com:11724/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge